spring:
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
  sql:
    init:
      platform: hsqldb

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true